import * as THREE from 'three';
const A=THREE.Group.prototype.add,R={sg:null,logo:null,vol:null,eau:null,labels:[],paper:[]};
function s(o){if(!o?.geometry)return null;o.geometry.computeBoundingBox?.();const b=o.geometry.boundingBox;if(!b)return null;const v=new THREE.Vector3();b.getSize(v);return v;}
function creamMap(src){const im=src?.image;if(!im?.width||!im?.height)return null;const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#E7E4DD';x.fillRect(0,0,c.width,c.height);x.globalCompositeOperation='destination-in';x.drawImage(im,0,0,c.width,c.height);x.globalCompositeOperation='source-over';const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.minFilter=THREE.LinearFilter;t.magFilter=THREE.LinearFilter;t.generateMipmaps=false;t.needsUpdate=true;return t;}
function graphiteMap(){const n=1024,c=document.createElement('canvas');c.width=c.height=n;const x=c.getContext('2d'),r=0x40,g=0x40,b=0x3D;x.fillStyle=`rgb(${r},${g},${b})`;x.fillRect(0,0,n,n);const d=x.getImageData(0,0,n,n);for(let i=0;i<d.data.length;i+=4){const q=(Math.random()-.5)*5;d.data[i]=Math.max(0,Math.min(255,r+q));d.data[i+1]=Math.max(0,Math.min(255,g+q*.96));d.data[i+2]=Math.max(0,Math.min(255,b+q*.88));}x.putImageData(d,0,0);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(3,3);t.colorSpace=THREE.SRGBColorSpace;t.needsUpdate=true;return t;}
function styleLabel(l){if(!l?.material?.map)return;if(!R.labels.includes(l))R.labels.push(l);l.scale.set(.92,.92,1);l.position.z=36.8;if(!l.userData.creamLift){l.position.y+=.10;l.userData.creamLift=true;}l.renderOrder=240;const m=creamMap(l.material.map);if(m)l.material.map=m;l.material.color?.set?.(0xffffff);l.material.opacity=1;l.material.transparent=true;l.material.depthTest=true;l.material.depthWrite=false;l.material.toneMapped=false;l.material.needsUpdate=true;}
THREE.Group.prototype.add=function(...os){for(const o of os){if(!o?.isMesh)continue;const z=s(o);if(!z)continue;if(o.material?.isMeshStandardMaterial&&o.material?.map)R.paper.push(o);if(Math.abs(z.x-108)<.7&&Math.abs(z.y-9.45)<.7)R.logo=o;if(Math.abs(z.x-92)<.7&&Math.abs(z.y-6)<.7){R.vol=o;R.sg=this;}if(Math.abs(z.x-58)<.7&&Math.abs(z.y-5)<.7)R.eau=o;if(Math.abs(z.x-32)<.8&&Math.abs(z.y-4.4)<.8)R.labels.push(o);}return A.apply(this,os)};
await import('./gift-set-v36.js?build=52');THREE.Group.prototype.add=A;
const gm=graphiteMap(),seen=new Set();R.paper.forEach(o=>{const m=o.material;if(!m||seen.has(m.uuid))return;seen.add(m.uuid);m.map=gm.clone();m.map.needsUpdate=true;m.color.set(0xffffff);m.roughness=.90;m.metalness=0;m.bumpMap=m.map;m.bumpScale=.10;m.needsUpdate=true;});
if(R.vol)R.vol.visible=false;if(R.eau)R.eau.visible=false;
if(R.logo){R.logo.scale.set(.50,.50,1);R.logo.position.z=-15.5;if(R.logo.material){const cm=creamMap(R.logo.material.map);if(cm)R.logo.material.map=cm;R.logo.material.color?.set?.(0xffffff);R.logo.material.opacity=1;R.logo.material.transparent=true;R.logo.material.depthTest=false;R.logo.material.depthWrite=false;R.logo.material.toneMapped=false;R.logo.material.needsUpdate=true;}}
if(document.fonts?.load){await Promise.allSettled([document.fonts.load('500 96px "Bodoni Moda"'),document.fonts.ready]);}
function textTex(t,fs,tr){const c=document.createElement('canvas');c.width=2000;c.height=360;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#E7E4DD';x.textBaseline='middle';x.fontKerning='normal';x.font=`500 ${fs}px "Bodoni Moda", Didot, "Times New Roman", serif`;const a=[...t],w=a.map(q=>x.measureText(q).width),T=w.reduce((p,q)=>p+q,0)+tr*(a.length-1);let p=(c.width-T)/2;a.forEach((q,i)=>{x.fillText(q,p,c.height/2);p+=w[i]+tr});const m=new THREE.CanvasTexture(c);m.colorSpace=THREE.SRGBColorSpace;m.minFilter=THREE.LinearFilter;m.magFilter=THREE.LinearFilter;m.generateMipmaps=false;m.needsUpdate=true;return m;}
function add(t,w,z,fs,tr,ord){const h=w/(2000/360),m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:textTex(t,fs,tr),transparent:true,opacity:1,toneMapped:false,depthTest:false,depthWrite:false,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.set(0,21.16,z);m.renderOrder=61000+ord;R.sg?.add(m);}
add('VOLUME I — KENOPSIA',84,30.2,98,6,1);
add('EAU DE PARFUM',52,39.0,82,5,2);
R.labels.forEach(styleLabel);
const B=THREE.Group.prototype.add;THREE.Group.prototype.add=function(...os){for(const o of os){if(!o?.isMesh)continue;const z=s(o);if(z&&Math.abs(z.x-32)<.8&&Math.abs(z.y-4.4)<.8)queueMicrotask(()=>styleLabel(o));}return B.apply(this,os)};
function syncLabels(){const v=Number(document.getElementById('ctrl-open')?.value??.82);R.labels.forEach(l=>l.visible=v>.34);requestAnimationFrame(syncLabels);}syncLabels();
